CREATE DATABASE EDUCANDOSA
GO
USE EDUCANDOSA
GO

CREATE TABLE USUARIOS(
 ID INT IDENTITY PRIMARY KEY NOT NULL,
 NOMBRE VARCHAR(60) NOT NULL,
 ROL VARCHAR(20) NULL,
 CEDULA CHAR(10) NOT NULL
)
GO
CREATE TABLE SOLICITUDES(
  ID INT IDENTITY PRIMARY KEY NOT NULL,  
  IDRESPONSBLE INT NOT NULL,
  FECHA DATETIME DEFAULT GETDATE() NOT NULL,
  CENTRO_COSTOS VARCHAR(30) NOT NULL,
  RUBRO_PRESUPUESTAL VARCHAR(30) NOT NULL
)
GO


CREATE TABLE ITEMS(
  ID INT IDENTITY PRIMARY KEY NOT NULL,
  NOMBREBIEN VARCHAR(60) NOT NULL,
  CANTIDAD FLOAT NOT NULL,
  VALOR_UNIDAD FLOAT NOT NULL,
  VALORTOTAL FLOAT NOT NULL,
  UNIDAD_MEDIDA VARCHAR(30) NOT NULL,
  IDSOLICITUD INT NOT NULL,
  IDFACTURA INT NOT NULL
)
GO


CREATE TABLE ORDER_CONTRACTUAL(
 ID INT IDENTITY PRIMARY KEY NOT NULL,
 NOM_PROVEEDOR VARCHAR(60) NOT NULL,
 FECHA_ORDEN DATETIME DEFAULT GETDATE() NOT NULL,
 MONTO_TOTAL FLOAT NOT NULL,
 FECHA_ENTREGA DATETIME NOT NULL,
 RUC VARCHAR(30) NOT NULL
)
GO

CREATE TABLE INVENTARIO(
 ID INT IDENTITY PRIMARY KEY NOT NULL,
 IDRESPOSABLE INT NOT NULL,
 FECHAENTREGA DATETIME NOT NULL,
 DIRECCION VARCHAR(100) NOT NULL,
 IDCOMPRA INT NOT NULL
 )
 GO
 CREATE TABLE SALIDA_ALMACEN(
  ID INT IDENTITY PRIMARY KEY NOT NULL,
  EMPLEADO VARCHAR(60) NOT NULL,
  FECHASALIDA DATETIME NOT NULL,
  FECHAENTREGA DATETIME NOT NULL,
  IDFACTURA INT NOT NULL
 )
 GO


 CREATE TABLE COMPRA(
  ID INT IDENTITY PRIMARY KEY NOT NULL,
  IDSOLICITUD INT NOT NULL,
  IDORDENCONTRACTUAL INT NOT NULL,
  IDINVENTARIO INT NOT NULL
 )
 GO
 
CREATE TABLE FACTURA(
 ID INT IDENTITY PRIMARY KEY NOT NULL,
 IDITEM INT NOT NULL,
 IDORDENCONTRACTUAL INT NOT NULL,
 TOTAL_BIENES INT NOT NULL,
 FECHA DATETIME NOT NULL,
 PROVEEDOR VARCHAR(60) NOT NULL,
 VALORTOTAL FLOAT NOT NULL
)
GO
ALTER TABLE FACTURA ADD FOREIGN KEY (IDITEM) REFERENCES ITEMS
ALTER TABLE FACTURA ADD FOREIGN KEY (IDORDENCONTRACTUAL) REFERENCES ORDER_CONTRACTUAL
ALTER TABLE SALIDA_ALMACEN ADD FOREIGN KEY (IDFACTURA) REFERENCES FACTURA
ALTER TABLE COMPRA ADD FOREIGN KEY (IDINVENTARIO) REFERENCES INVENTARIO
 ALTER TABLE COMPRA ADD FOREIGN KEY (IDORDENCONTRACTUAL) REFERENCES ORDER_CONTRACTUAL
 ALTER TABLE COMPRA ADD FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUDES
 ALTER TABLE SOLICITUDES ADD FOREIGN KEY (IDRESPONSBLE) REFERENCES USUARIOS 
 ALTER TABLE ITEMS ADD FOREIGN KEY (IDSOLICITUD) REFERENCES SOLICITUDES 
 go

/* USUARIOS*/
SELECT * FROM USUARIOS
GO


INSERT INTO USUARIOS VALUES ('Velasquez Cordova, Rony Javier','Administrador','72450897')
INSERT INTO USUARIOS VALUES ('Vergara García Milton Raúl','Administrador','75698236')
INSERT INTO USUARIOS VALUES ('Escobar Zavaleta, Gruber Omar ','Administrador','74589632')
INSERT INTO USUARIOS VALUES ('Diaz Cardenas, Brice Martin Sebastian','Administrador','79863254')
INSERT INTO USUARIOS VALUES ('Garcia Sedamano, Michael Enrique','Administrador','72460589')
GO
--PROCEDURES--
CREATE PROC PROC_INSERT_USERS(
@NOMBRE VARCHAR(60) ,
@ROL VARCHAR(20) ,
@CEDULA CHAR(10))
AS
 INSERT INTO USUARIOS(NOMBRE,ROL,CEDULA) VALUES (@NOMBRE,@ROL,@CEDULA)
GO
EXEC PROC_INSERT_USERS 'Ana','ADMIN','72450897'
GO
CREATE PROC COUNT_USERS
AS
SELECT COUNT(*) as NUMERO FROM USUARIOS
GO

CREATE PROC LIST_USERS
AS 
SELECT * FROM USUARIOS

GO
EXEC LIST_USERS
GO

/*SOLICITUDES*/
 select * from SOLICITUDES
 INSERT INTO SOLICITUDES VALUES (3,GETDATE()-579,'Planeamiento','Operacionales')
INSERT INTO SOLICITUDES VALUES (2,GETDATE()-598,'Ventas','Capital')
INSERT INTO SOLICITUDES VALUES (2,GETDATE()-432,'Ventas','Capital')
INSERT INTO SOLICITUDES VALUES (2,GETDATE()-932,'Ventas','Capital')
INSERT INTO SOLICITUDES VALUES (2,GETDATE()-502,'Gerencia de RRHH','Operacionales')
INSERT INTO SOLICITUDES VALUES (1,GETDATE()-1156,'Planeamiento','Operacionales')
INSERT INTO SOLICITUDES VALUES (3,GETDATE()-540,'Marketing','Capital')
INSERT INTO SOLICITUDES VALUES (3,GETDATE()-1725,'Dirección General','Operacionales')
INSERT INTO SOLICITUDES VALUES (2,GETDATE()-1267,'Dirección General','Operacionales')
INSERT INTO SOLICITUDES VALUES (4,GETDATE()-1873,'Operaciones','Trasnferencias')
INSERT INTO SOLICITUDES VALUES (3,GETDATE()-1834,'Dirección General','Operacionales')
INSERT INTO SOLICITUDES VALUES (5,GETDATE()-1258,'Marketing','Capital')
INSERT INTO SOLICITUDES VALUES (5,GETDATE()-1713,'Operaciones','Trasnferencias')
INSERT INTO SOLICITUDES VALUES (1,GETDATE()-1235,'Gerencia de RRHH','Operacionales')
INSERT INTO SOLICITUDES VALUES (4,GETDATE()-1734,'Marketing','Capital')
INSERT INTO SOLICITUDES VALUES (1,GETDATE()-1985,'Planeamiento','Operacionales')
INSERT INTO SOLICITUDES VALUES (5,GETDATE()-570,'Marketing','Capital')
INSERT INTO SOLICITUDES VALUES (3,GETDATE()-1929,'Gerencia de RRHH','Operacionales')
INSERT INTO SOLICITUDES VALUES (4,GETDATE()-539,'Gerencia de RRHH','Operacionales')
INSERT INTO SOLICITUDES VALUES (5,GETDATE()-1097,'Marketing','Capital')
INSERT INTO SOLICITUDES VALUES (5,GETDATE()-1651,'Ventas','Capital')
INSERT INTO SOLICITUDES VALUES (2,GETDATE()-632,'Planeamiento','Operacionales')
INSERT INTO SOLICITUDES VALUES (1,GETDATE()-871,'Marketing','Capital')
INSERT INTO SOLICITUDES VALUES (1,GETDATE()-1774,'Gerencia de RRHH','Operacionales')
INSERT INTO SOLICITUDES VALUES (4,GETDATE()-810,'Ventas','Capital')
INSERT INTO SOLICITUDES VALUES (4,GETDATE()-970,'Planeamiento','Operacionales')
INSERT INTO SOLICITUDES VALUES (3,GETDATE()-1156,'Operaciones','Trasnferencias')

GO
ALTER TABLE SOLICITUDES ADD COL_STATUS BIT  NULL;
GO


--PROC SOLICITUDES--
CREATE PROC COUNT_SOLICITUDES
AS
SELECT COUNT(*) AS NUMERO FROM SOLICITUDES
GO

/*INVENTARIO*/
INSERT INTO SALIDA_ALMACEN VALUES (1,GETDATE(),GETDATE(),2)
INSERT INTO SALIDA_ALMACEN VALUES (2,GETDATE(),GETDATE(),2)
INSERT INTO SALIDA_ALMACEN VALUES (1,GETDATE(),GETDATE(),3)
INSERT INTO SALIDA_ALMACEN VALUES (1,GETDATE(),GETDATE(),4)
GO

--PROC INVENTARIO--
CREATE PROC COUNT_INVENTARIO
AS 
 SELECT COUNT(*) AS NUMERO FROM SOLICITUDES
GO
select COUNT(CENTRO_COSTOS)/COUNT(*) as RESULTADO
from SOLICITUDES  where IDRESPONSBLE = 3
exec COUNT_INVENTARIO
GO
/**/
SELECT * FROM SOLICITUDES
SELECT S.CENTRO_COSTOS, COUNT(S.CENTRO_COSTOS) AS NUMERO FROM SOLICITUDES AS S GROUP BY CENTRO_COSTOS
GO
/*FACTURAS*/

--PROC FACTURAS--
CREATE PROC COUNT_FACT
AS
SELECT COUNT(*) AS NUMERO FROM FACTURA
GO
/*ITEMS*/
SELECT * FROM ITEMS

INSERT INTO ITEMS VALUES ('Computadoras',15,1400.5,21007.5,'Unidades',1,1)
INSERT INTO ITEMS VALUES ('Mouse',15,30,450,'Unidades',3,3)
INSERT INTO ITEMS VALUES ('Teclado',15,25,375,'Unidades',5,2)
INSERT INTO ITEMS VALUES ('Escritorios',5,150,750,'Unidades',27,2)
INSERT INTO ITEMS VALUES ('Teléfonos',2,600,1200,'Unidades',20,4)
INSERT INTO ITEMS VALUES ('Sillas',15,300,4500,'Unidades',5,3)
INSERT INTO ITEMS VALUES ('Impresoras',2,200,400,'Unidades',6,1)
INSERT INTO ITEMS VALUES ('Archivadores',25,1,25,'Unidades',18,1)
INSERT INTO ITEMS VALUES ('Plumones',30,5,150,'Unidades',15,2)
INSERT INTO ITEMS VALUES ('Hojas A4',1000,40,40000,'Paquetes',8,4)
INSERT INTO ITEMS VALUES ('Clips',1000,1,1000,'Unidades',6,3)
INSERT INTO ITEMS VALUES ('Perforadores',2,25,50,'Unidades',5,3)
INSERT INTO ITEMS VALUES ('Dispensadores',1,150,150,'Unidades',15,2)
INSERT INTO ITEMS VALUES ('Folders',300,2,600,'Unidades',8,2)
GO
--PROC ITEMS--


/*FACTURAS*/
SELECT * FROM FACTURA

--PROC FACTURAS--
GO
/*salida almacen*/

select * from SALIDA_ALMACEN
INSERT INTO SALIDA_ALMACEN VALUES('Velasquez Cordova, Rony Javier',GETDATE()-740,GETDATE()+745,1)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-961,GETDATE()+966,2)
INSERT INTO SALIDA_ALMACEN VALUES('Escobar Zavaleta, Gruber Omar ',GETDATE()-671,GETDATE()+676,1)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-198,GETDATE()+203,1)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-653,GETDATE()+658,2)
INSERT INTO SALIDA_ALMACEN VALUES('Escobar Zavaleta, Gruber Omar ',GETDATE()-634,GETDATE()+639,1)
INSERT INTO SALIDA_ALMACEN VALUES('Vergara García Milton Raúl',GETDATE()-661,GETDATE()+666,2)
INSERT INTO SALIDA_ALMACEN VALUES('Velasquez Cordova, Rony Javier',GETDATE()-256,GETDATE()+261,3)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-373,GETDATE()+378,1)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-869,GETDATE()+874,2)
INSERT INTO SALIDA_ALMACEN VALUES('Velasquez Cordova, Rony Javier',GETDATE()-166,GETDATE()+171,3)
INSERT INTO SALIDA_ALMACEN VALUES('Vergara García Milton Raúl',GETDATE()-124,GETDATE()+129,5)
INSERT INTO SALIDA_ALMACEN VALUES('Velasquez Cordova, Rony Javier',GETDATE()-440,GETDATE()+445,3)
INSERT INTO SALIDA_ALMACEN VALUES('Escobar Zavaleta, Gruber Omar ',GETDATE()-234,GETDATE()+239,6)
INSERT INTO SALIDA_ALMACEN VALUES('Escobar Zavaleta, Gruber Omar ',GETDATE()-688,GETDATE()+693,6)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-117,GETDATE()+122,7)
INSERT INTO SALIDA_ALMACEN VALUES('Velasquez Cordova, Rony Javier',GETDATE()-913,GETDATE()+918,7)
INSERT INTO SALIDA_ALMACEN VALUES('Vergara García Milton Raúl',GETDATE()-751,GETDATE()+756,5)
INSERT INTO SALIDA_ALMACEN VALUES('Velasquez Cordova, Rony Javier',GETDATE()-753,GETDATE()+758,5)
INSERT INTO SALIDA_ALMACEN VALUES('Escobar Zavaleta, Gruber Omar ',GETDATE()-478,GETDATE()+483,6)
INSERT INTO SALIDA_ALMACEN VALUES('Escobar Zavaleta, Gruber Omar ',GETDATE()-135,GETDATE()+140,7)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-212,GETDATE()+217,10)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-511,GETDATE()+516,8)
INSERT INTO SALIDA_ALMACEN VALUES('Diaz Cardenas, Brice Martin Sebastian',GETDATE()-774,GETDATE()+779,8)
GO

select * from ORDER_CONTRACTUAL
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 1',GETDATE()-262,84099,GETDATE()+267,'32385965')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 2',GETDATE()-844,98916,GETDATE()+849,'22224545456')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 3',GETDATE()-540,68555,GETDATE()+545,'54654654545')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 4',GETDATE()-445,43132,GETDATE()+450,'2455454')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 5',GETDATE()-462,39832,GETDATE()+467,'65656556656')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 6',GETDATE()-162,5623,GETDATE()+167,'21313132323')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 7',GETDATE()-251,13351,GETDATE()+256,'1213213132')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 8',GETDATE()-901,7383,GETDATE()+906,'132132323')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 9',GETDATE()-413,18417,GETDATE()+418,'549565656')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 10',GETDATE()-406,56303,GETDATE()+411,'2165341345')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 11',GETDATE()-687,35060,GETDATE()+692,'24165459686')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 12',GETDATE()-505,92099,GETDATE()+510,'12698963')
INSERT INTO ORDER_CONTRACTUAL VALUES ('Provedor 13',GETDATE()-468,99422,GETDATE()+473,'4165456456')

GO

SELECT * FROM INVENTARIO
INSERT INTO INVENTARIO VALUES (1,GETDATE()+116,'',1)
INSERT INTO INVENTARIO VALUES (3,GETDATE()+186,'',2)
INSERT INTO INVENTARIO VALUES (2,GETDATE()+135,'',1)
INSERT INTO INVENTARIO VALUES (5,GETDATE()+183,'',2)
INSERT INTO INVENTARIO VALUES (4,GETDATE()+119,'',3)
INSERT INTO INVENTARIO VALUES (3,GETDATE()+138,'',4)
INSERT INTO INVENTARIO VALUES (2,GETDATE()+199,'',5)
INSERT INTO INVENTARIO VALUES (2,GETDATE()+119,'',4)
INSERT INTO INVENTARIO VALUES (1,GETDATE()+118,'',4)
INSERT INTO INVENTARIO VALUES (2,GETDATE()+188,'',4)
INSERT INTO INVENTARIO VALUES (3,GETDATE()+199,'',1)
INSERT INTO INVENTARIO VALUES (2,GETDATE()+195,'',2)
INSERT INTO INVENTARIO VALUES (4,GETDATE()+175,'',2)
INSERT INTO INVENTARIO VALUES (4,GETDATE()+168,'',3)

select * from COMPRA
SELECT * FROM ORDER_CONTRACTUAL
SELECT * FROM INVENTARIO
INSERT INTO COMPRA VALUES (2,3,16);
INSERT INTO COMPRA VALUES (5,1,17);
INSERT INTO COMPRA VALUES (3,5,29);
INSERT INTO COMPRA VALUES (4,4,22);
INSERT INTO COMPRA VALUES (7,2,23);
INSERT INTO COMPRA VALUES (9,9,20);
GO

SELECT * FROM FACTURA

INSERT INTO FACTURA VALUES(1,1,20,GETDATE(),'Proveddor 2',2000)
INSERT INTO FACTURA VALUES(2,2,21,GETDATE(),'Proveddor 1',2500)
INSERT INTO FACTURA VALUES(3,3,22,GETDATE(),'Proveddor 3',3000)
INSERT INTO FACTURA VALUES(4,4,16,GETDATE(),'Proveddor 4',400)
INSERT INTO FACTURA VALUES(5,5,17,GETDATE(),'Proveddor 5',4500)
GO

CREATE VIEW PROVEDOR_DETALLE
AS
SELECT O.NOM_PROVEEDOR,O.MONTO_TOTAL,O.FECHA_ORDEN,O.RUC FROM INVENTARIO AS I  FULL JOIN   COMPRA AS C  
ON C.ID=I.IDCOMPRA FULL JOIN  ORDER_CONTRACTUAL AS O ON O.ID=I.IDCOMPRA
GO

CREATE PROC DETALLE_VIEW
AS
SELECT * FROM PROVEDOR_DETALLE
GO
EXEC DETALLE_VIEW

CREATE NONCLUSTERED INDEX FACTURA_ORDEN
ON FACTURA (VALORTOTAL ASC ) 

GO

CREATE PROC MONTO_DEC
AS
SELECT VALORTOTAL FROM FACTURA
GO


EXEC MONTO_DEC

CREATE INDEX IDX_CUSTOMER_LAST_NAME
ON SOLICITUDES (CENTRO_COSTOS);
GO
SELECT * FROM SOLICITUDES

CREATE INDEX IDX_USER_NAME
ON USUARIOS (NOMBRE);
GO
SELECT * FROM USUARIOS



CREATE INDEX IDX_USUARIO
ON SOLICITUDES (CENTRO_COSTOS);
GO


SELECT * FROM ITEMS
GO

CREATE PROC DETALLE_FACTURA
AS
SELECT I.NOMBREBIEN,I.CANTIDAD,I.VALORTOTAL,F.FECHA FROM FACTURA AS F INNER JOIN ITEMS AS I ON I.ID=F.IDITEM
GO

EXEC DETALLE_FACTURA

/**/

Create table historial
(fecha date,
descripcion varchar(100), 
usuario varchar(20))
GO

CREATE trigger TR_AuditoriaP_Eliminar
ON SOLICITUDES
FOR DELETE
AS 
	BEGIN
		INSERT historial SELECT getdate(),'registro Eliminado',SYSTEM_USER from deleted
	END;
GO

CREATE PROC LISTA_AUD
AS
SELECT * FROM historial
GO

EXEC LISTA_AUD
